name: Flake8 Linting

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up python environment
      uses: actions/setup-python@v2
    - name: Install python dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 pytest coverage requests
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 EventStreams/src/ --count --max-line-length=127 --statistics
